# Run `travis lint` when changing this file to avoid breaking the build.
# Default JDK is really old: 1.8.0_31; Trusty's is less old: 1.8.0_51
# https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments
dist: trusty
sudo: false
language: java
jdk: oraclejdk8
before_install:
  # Parameters used during release
  - git config user.name "$GH_USER"
  - git config user.email "$GH_USER_EMAIL"
  # setup https authentication credentials, used by ./mvnw release:prepare
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://$GH_TOKEN:@github.com" > .git/credentials

install:
  # Override default travis to use the maven wrapper
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - ./travis/publish.sh

cache:
  directories:
  - $HOME/.m2

#matrix:
# include:
   # - os: linux
   #  jdk: oraclejdk8
   #  addons:
   #    apt:
   #      packages:
   #        - oracle-java8-installer
   #- os: linux
   #  jdk: openjdk8
   #- os: linux
   #  jdk: openjdk11

# Don't build release tags. This avoids publish conflicts because the version commit exists both on master and the release tag.
# See https://github.com/travis-ci/travis-ci/issues/1532
branches:
  except:
    - /^[0-9]/

env:
  global:
  # Ex. travis encrypt BINTRAY_USER=your_github_account
  - secure: "VeTOgXwhZLf8uwlnYpB9tuY+NV6kiooRN0FMDoWCXuPPSz/tX2mqmshBXDYsJu0EcRtZb21MkbQwbdJ8Th9K/bvj4sGNK1PrBm9Hmz6e2AvAcxn3ROv86GMTkd7O25OsipTT+/qWrbR3s3lHQxYo5WMsrlEmJ/EF5y5Go5wx90c="
  # Ex. travis encrypt BINTRAY_KEY=xxx-https://bintray.com/profile/edit-xxx --add
  - secure: "WND+fjAqpdHArSbXAK7l0dpQLrX0hL/XymV02rhe0pVT1g0J1V32ncqDCVnn/73wTiECTen6y3o1vq3ByIdT9tUErt3o8oEROQsI/cVX9IhvJ/DtcW1lqafXKmQZwDQsifVxhKroW1VuZQbGrKnqVUzfqx5OzxgoNVWpkkxhf50="
  # Ex. travis encrypt GH_USER_EMAIL=for_github@domain.com --add
  - secure: "LdZtaCS9k/00rY2EIltZ1tW9Js8cKyDKJxESZd70R54KhSEhwSk6+NFR3BFag93mhY4UnzTVSegN/ENmrRhXb6TRu4sWdEHE1VvvjswNhF12duBCHNItpglnHwNwNSfyjYCED2ZrqLwx1snBokLxibmuGesOTRqPYQJ9gG4QOi5ybiQndi8sMbyhbLE3XcU920YviN7AW4dWNLIaz4Xjf3zPfMPd5xKB/+pYdGF2M/NTzYjHBo29MQHk/vs1mitGYd5qYlIef/7A/o1FUQjvDJ3Y8vitaSMR+Uu4PIhk4zQBeIr71j7c7QNq1+srhsrGmmWF4P08Y7has9uqpJ22xgv3XDUAkR+iS4Bm/RnfkEg+4IuFSk3bAhYdoldibHSpuh+iIxfdcDuJIklINg/24ELHHvkRoYYfEPSaVUKZ4sMKCcOfC6w2K2DQbQMx0GhxNqPbmpTymeVnF1p1Knz2hwjXAufl2LQ10u776Ri02GlQjPivd+QEtROJzFuJXHXGFqaXX8hu+0GjgU/FmetEtqrz9KMCShUWzsCc5JYESsviwtQuGWCJtHEzWBCil+Y7QK/FxXHZeURNPSVruyLGuJ0IZISF9mz53w6yK354M3QjHVP/KPime1muGapo7hSalA14h0sW+5fqB/ekM908WkAef+SIQKdn4fI1N2QnW+w="
    # Ex. travis encrypt GH_USER=your_github_account --add
  - secure: "JWTxJcsCJk1FWZ4QXMsY95JW8eDFaeM0vWQ+K00FEWk56q4hUExhsslfpnue1cbjqt7dtzS4FjzuZ5TcOxVA8Qndksa7Yay0VLZH7FfM3JCWI/hlvHVfK7VPCHXYivKGFdgBMQw6WhFtkjOYtFjNBq1gNpXDIeDoJZsxDQP2oVWN7xu/u/qM5YS4uT2aq4GNGGwxMJBLoqzXivq19fQVdPm3n/zuHrARHeNiydpZ5rnSRANRXYSGJud6On9PZv0QHAxxVWJ8neKSc8bZIt4XuznZe/btQjhviQ2W3fnDwahnXuJsBmkAAIIk5RuSl1Z+K0j0jkaOMp4l7ZUMktTqvn9lFF+xIvZWAEF6qm7c8ingGKH1emFKrNb5zlAAH1r2tFTG+zoMtBR+VSEHWVpBaULvvQBH/5kFA95I4T/zTGHRWpYyG9wEDpSy/8Uf9LL9D6n2dFZFMpc9zuqcyYVw25wzzHk8c9st1J6//6S9PDh7AnnWhnSRxCeo38LpgwgKXRW6d3dIECMEER9l7QflGcQldEWK8WCiae3xe3q4TjuteqVimZDDqExpo6/x8wx1Lt2XiXXxurZc/UjGi2HYYmrAEWoqkfuELaGUC6d1HFVJPRwZAyWOW8B4F077LSh94ymhxuv+ZgySFK8ah1kw8n0tfYmljQ6BawDDl8DYu+M="
  # Ex. travis encrypt GH_TOKEN=XXX-https://github.com/settings/tokens-XXX --add
  - secure: "i5UfUQypvtl75y2zoUAHewvCq/GiA4tjopwurF1L2Pp7TbhVftMB5YUuwNIfhbvZs+nx8aOxiOt2fIzaEqy1OD47cltHTa6VPRdeVdG0S0Fr1nCdjxHtCfOdoxf4XZ7O1es8Y2hn5AhcJuW0nTtqukaGDKmL6CuY8+urGQN1WkH475Yy3oFEB/zppApgocn3F60M9doZCa+zJxwSlLwIXTE5pcXIKSZcN6jFqMg1oywgVKUKN6SAfSFhzCrAnJ62USVeeD+7564Bc7TSfPbKCePoRp5/Wgvw/zBx6oQf0R84DghvCx++/dUOTE76yavgdtYN2nOYLGgj0EBLD2HGOF0X822/niVnhnLEsDdywqgaBaUMPGNFqISyALjEk/9nUqalpfcm0pHDzT874uaGR5pskzGMMRdZDPXCKg4dvAwSQf2GDbEk4gwlcf/TFjkn+wHQaJ0UlzTOxH/bdLCTp4+oFwN5N+m9zwf4fJNbNOrh0HcIVbXClRAoqRKx2uN0Yy2LlSi0CJJB9wECoLqVLd4rkhfUTqC4Ssz41x3PQwjzVg6tf59OLt3iwrP874yadl4uXoPCrR+tctz1s6wyxXOpWXZLr5docYEQr3lWxqDHRn/B2qiFsP/a0dFeJK/u/tRijntLOTS2u7V6onSbgb63E15bqA+2mJ/Z1ozpzi8="
  # Ex. travis encrypt SONATYPE_USER=your_sonatype_account
  - secure: "ONAU76S0WBGcQGf0mr7KxKQjFvhhu73GNuQG8j47pxhJojNlNpWBbu+EGkgaInWKMtO89iBtpicVlXZc06HtbSqv7L93gbMo+xgp5daLlQg4gocDixjB1I2oPPITFFoztu76nOA1IBWRLTKu+w+Y2tKOmzWm+5v2UKD6fz7SYoo="
  # Ex. travis encrypt SONATYPE_PASSWORD=your_sonatype_password
  - secure: "UaVTxnw8klS36WLAdcmubqrHIgS4o5NcIqQMPIihk0tv3VEvCJSGvc2b7EPyQZMvm5TR3mXq5IJUAHp8j3seAHfYWmLIZWzvn7Y5mLRw8Kh9up7GzXl8Idui0AEHAAL2mfvE9smlOKPS5D13LKc6tOGFER66itHW3Jg1QoijDmQ="

