language: java

os:
  - linux

jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8

install:
  - mvn install dependency:go-offline -Pci -Pskip-formatter -DskipTests=true -fn -q

script:
  - mvn clean install -Pci -B
