#
# Copyright 2012-2020 The Feign Authors
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
# in compliance with the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License
# is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied. See the License for the specific language governing permissions and limitations under
# the License.
#

# common executors
executors:
  java:
    parameters:
      jdk:
        description: 'jdk version to use'
        default: '8'
        type: string
    docker:
      - image: circleci/openjdk:<<parameters.jdk>>

# common commands
commands:
  resolve-dependencies:
    description: 'Download and prepare all dependencies'
    steps:
      - run: mvn dependency:resolve-plugins go-offline:resolve-dependencies -DskipTests=true
  verify-formatting:
    steps:
      - run:
          name: 'Verify formatting'
          command: |
            scripts/no-git-changes.sh
  configure-gpg:
    steps:
      - run:
          name: 'Configure GPG keys'
          command: |
            echo -e "$GPG_KEY" | gpg --batch --no-tty --import --yes
  nexus-deploy:
    steps:
      - run:
          name: 'Deploy Core Modules Sonatype'
          command: |
            mvn -nsu -s .circleci/settings.xml -P release -pl -:feign-benchmark -DskipTests=true deploy
  jdk11-build:
    steps:
      - run:
          name: 'Build JDK 11 Modules'
          command: |
            mvn -B -nsu -s ./travis/settings.xml -P java11 -pl :feign-java11 -am -DskipTests=true install
  jdk11-deploy:
    steps:
      - run:
          name: 'Deploy JDK 11 Modules to Sonatype'
          command: |
            mvn -B -nsu -s ./travis/settings.xml -P release,java11 -pl :feign-java11 -DskipTests=true deploy

# our job defaults
defaults: &defaults
  working_directory: ~/feign
  environment:
    # Customize the JVM maximum heap limit
    MAVEN_OPTS: -Xmx3200m

version: 2.1

jobs:
  build:
    parameters:
      jdk:
        description: 'jdk version to use'
        default: '8'
        type: string
    executor:
      name: java
      version: <<parameters.version>>
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - feign-dependencies-{{ checksum "pom.xml" }}
            - feign-dependencies-
      - resolve-dependencies
      - save_cache:
          paths:
            - ~/.m2
          key: feign-dependencies-{{ checksum "pom.xml" }}
      - run:
          name: 'Test'
          command: |
            mvn -o test
      - verify-formatting

  deploy:
    parameters:
      jdk:
        description: 'jdk version to use'
        default: '8'
        type: string
    executor:
      name: java
      version: <<parameters.version>>
    steps:
      - checkout
      - restore_cache:
          keys:
            - feign-dependencies-{{ checksum "pom.xml" }}
            - feign-dependencies-
      - resolve-dependencies
      - configure-gpg
      - nexus-deploy

workflows:
  version: 2
  build:
    jobs:
      - build:
          jdk: 8
      - build:
          jdk: 11
      - build:
          jdk: 14




